#/bin/bash
#PBS -q ftp
#PBS -l select=1:ncpus=1:mem=10g
#PBS -l walltime=2:00:00
#PBS -N zen_update
#PBS -S /bin/bash

signal_handler() {
	pkill --parent "${$}"
}
trap signal_handler EXIT

cd /home1/datahome/villien/project_hub/zenodo-tools

. /appli/anaconda/latest/etc/profile.d/conda.sh
conda activate /home1/datawork/villien/conda-env/zenodo_env
python3 zenodo-upload.py -ecsv -pcsv /home1/datahome/villien/csv_session/session_to_update_2024.csv -um -pmj metadata/metadata.json

conda deactivate

qstat -f $PBS_JOBID
