#/bin/bash
#PBS -q ftp
#PBS -l select=1:ncpus=1:mem=10g
#PBS -l walltime=2:00:00
#PBS -m b
#PBS -o ./output.txt
#PBS -e ./error.txt
#PBS -N zen_down
#PBS -S /bin/bash
#PBS -J 1-8


signal_handler() {
	pkill --parent "${$}"
}
trap signal_handler EXIT

cd /home1/datahome/villien/project_hub/zenodo-tools

. /appli/anaconda/latest/etc/profile.d/conda.sh
conda activate /home1/datawork/villien/conda-env/zenodo_env

python3 zenodo-download.py -ecsv -pcsv /home1/datahome/villien/csv_session/stleu_session.csv -dr -dp -po /home1/datawork/villien/plancha-session -ip $PBS_ARRAY_INDEX > output_${PBS_ARRAY_INDEX}.txt
conda deactivate

qstat -f $PBS_JOBID
