#/bin/bash
#PBS -q ftp
#PBS -l select=1:ncpus=1:mem=10g
#PBS -l walltime=2:00:00
#PBS -N zen_down
#PBS -S /bin/bash

signal_handler() {
	pkill --parent "${$}"
}
trap signal_handler EXIT

cd /home1/datahome/villien/project_hub/zenodo-tools

. /appli/anaconda/latest/etc/profile.d/conda.sh
conda activate /home1/datawork/villien/conda-env/zenodo_env

python3 zenodo-download.py -ename 20231208_REU-ST-LEU_UAV-01_03 -dr -dp -po /home/ifremer-rbe-doi-rummo/drone/drone_serge
conda deactivate

qstat -f $PBS_JOBID
